training_data_paths:
- "/home/kashif/.gluonts/datasets/electricity/train/data.json.gz"
- "/home/kashif/.gluonts/datasets/traffic/train/data.json.gz"
frequencies:
- "1H"
- "H"
probabilities:
- 0.9
- 0.1
context_length: 512
prediction_length: 64
min_past: 60
max_steps: 2000
save_steps: 100_000
logging_steps: 1
per_device_train_batch_size: 32
learning_rate: 0.001
optim: adamw_torch_fused
num_samples: 20
shuffle_buffer_length: 8
gradient_accumulation_steps: 2
model_id: amazon/chronos-t5-small
model_type: seq2seq
random_init: true
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: true
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.0
dataloader_num_workers: 0
max_missing_prop: 0.9
use_eos_token: true
logging_first_step: true
logging_strategy: steps