training_data_paths:
- "~/.gluonts/datasets/electricity/train/data.json.gz"
- "~/.gluonts/datasets/traffic/train/data.json.gz"
- "~/.gluonts/datasets/australian_electricity_demand/train/data.json.gz"
- "~/.gluonts/datasets/car_parts_without_missing/train/data.json.gz"
- "~/.gluonts/datasets/london_smart_meters_without_missing/train/data.json.gz"
frequencies:
- "1H"
- "H"
- "30T"
- "1M"
- "30T"
probabilities:
- 0.20
- 0.20
- 0.20
- 0.05
- 0.35
context_length: 512
prediction_length: 64
min_past: 60
max_steps: 10_000
per_device_train_batch_size: 32
max_missing_prop: 0.9
model_id: amazon/chronos-t5-small
model_type: seq2seq
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
use_eos_token: true
num_samples: 20
num_workers: 6